# Generated by Django 6.0.4 on 2026-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
    ]
