# Generated by Django 5.2.13 on 2026-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_house_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={
                "ordering": ["-active", "name"],
                "verbose_name": "Дом",
                "verbose_name_plural": "Дома",
            },
        ),
        migrations.AlterField(
            model_name="house",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
