# Generated by Django 6.0.4 on 2026-04-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_alter_house_options"),
        ("houses", "0005_alter_house_options_alter_house_id"),
    ]

    operations = []
