# Generated by Django 6.0.4 on 2026-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_house_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Количество спален'),
        ),
    ]
