# Generated by Django 6.0.4 on 2026-04-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_house_bedrooms'),
        ('houses', '0006_merge_20260423_1714'),
    ]

    operations = [
    ]
