# Generated by Django 6.0.4 on 2026-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_merge_0006_house_bedrooms_0006_merge_20260423_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
